<div id="<?php echo $widgetId; ?>"
     class="col-md-<?php echo $params['span']; ?> widget <?php echo $widgetType; ?>"
     data-widget-type="<?php echo $widgetType; ?>"
     data-params='<?php echo $this->json($params)?>'>
</div>
<script type="text/template" id="<?php echo $widgetId; ?>Tpl">
    <div class="widgetContainer">
        <div class="text">
            <h1 class="title"><?php echo $params['title']; ?> <?php if ($params['subtitle']):?><br/><small><?php echo $params['subtitle']; ?></small><?php endif?></h1>
        </div>

		<table>
		<% var rows = 5; %>
		<% var cols = 1 + (data.length - 1) / rows; %>
		<% for (var r = 0; r < rows; ++r) { %>
			<tr>
			<% for (var c = 0; c < cols; ++c) { %>
				<% var d = data[c * rows + r]; %>
				<% if (d) { %>
				<td><div class="service service-state-<%= d.state %>"><%= d.name.replace(/^Finn\.Crm\.Services\./ig, '') %></div></td>
				<% } %>
			<% } %>
			</tr>
		<% } %>
		</table>
    </div>
</script>