language: php
cache: bundler

php:
  - "5.5"
  - "5.4"

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - rake build setEnv[testing] ci

notifications:
  email: true